<?php

namespace Database\Seeders\Quest;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BlankQuestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('blank_quests')->insert([
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой язык разметки используется для создания структуры веб-страниц?',
                'correct' => '["html"]',
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Как называется протокол, используемый для безопасной передачи данных в вебе? (аббревиатура)',
                'correct' => '["https", "ssl", "tls"]',
                'difficulty' => 40,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод HTTP используется для получения данных от сервера?',
                'correct' => '["get"]',
                'difficulty' => 35,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Как называется технология для стилизации веб-страниц? (аббревиатура)',
                'correct' => '["css"]',
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тег HTML используется для подключения JavaScript к странице?',
                'correct' => '["<script>", "script"]',
                'difficulty' => 30,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Как называется объектная модель документа, представляющая структуру HTML? (аббревиатура)',
                'correct' => '["dom"]',
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой системой контроля версий чаще всего пользуются разработчики? (название)',
                'correct' => '["git"]',
                'difficulty' => 45,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какая функция в PHP выводит данные в поток вывода?',
                'correct' => '["echo", "print"]',
                'difficulty' => 20,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Как называется технология для асинхронных запросов в JavaScript? (аббревиатура)',
                'correct' => '["ajax"]',
                'difficulty' => 30,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой заголовок HTTP используется для перенаправления браузера?',
                'correct' => '["location"]',
                'difficulty' => 15,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой язык программирования чаще всего используется для создания динамических веб-страниц на стороне сервера?',
                'correct' => '["php", "python", "javascript", "ruby"]',
                'difficulty' => 40,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой фреймворк на JavaScript используется для создания пользовательских интерфейсов?',
                'correct' => '["react", "angular", "vue"]',
                'difficulty' => 30,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод HTTP используется для отправки данных на сервер, например, при отправке формы?',
                'correct' => '["post"]',
                'difficulty' => 35,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой инструмент используется для управления зависимостями в проектах на JavaScript?',
                'correct' => '["npm", "yarn"]',
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тег HTML используется для создания ссылок?',
                'correct' => '["<a>", "a"]',
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой язык используется для написания стилей в веб-разработке?',
                'correct' => '["css"]',
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой HTTP-код означает "Страница не найдена"?',
                'correct' => '["404"]',
                'difficulty' => 45,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тег HTML используется для вставки изображений?',
                'correct' => '["<img>", "img"]',
                'difficulty' => 40,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой язык используется для создания интерактивных элементов на веб-страницах?',
                'correct' => '["javascript"]',
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой HTTP-код означает "Успешный запрос"?',
                'correct' => '["200"]',
                'difficulty' => 45,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой язык используется для написания сценариев на стороне сервера в Node.js?',
                'correct' => '["javascript"]',
                'difficulty' => 30,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой инструмент используется для автоматизации задач в веб-разработке, таких как минификация CSS и JavaScript?',
                'correct' => '["webpack", "gulp", "grunt"]',
                'difficulty' => 20,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой HTTP-код означает "Внутренняя ошибка сервера"?',
                'correct' => '["500"]',
                'difficulty' => 40,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тег HTML используется для создания таблиц?',
                'correct' => '["<table>", "table"]',
                'difficulty' => 45,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой язык используется для создания запросов к базам данных в веб-приложениях?',
                'correct' => '["sql"]',
                'difficulty' => 35,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод JavaScript используется для добавления нового элемента в конец массива?',
                'correct' => '["push"]',
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой фреймворк на Python используется для веб-разработки?',
                'correct' => '["django", "flask"]',
                'difficulty' => 20,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тег HTML используется для создания списка с точками?',
                'correct' => '["<ul>", "ul"]',
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой HTTP-код означает "Доступ запрещён"?',
                'correct' => '["403"]',
                'difficulty' => 40,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод JavaScript используется для преобразования JSON-строки в объект?',
                'correct' => '["json.parse"]',
                'difficulty' => 30,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тег HTML используется для создания заголовка первого уровня?',
                'correct' => '["<h1>", "h1"]',
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод JavaScript используется для поиска элемента по его идентификатору?',
                'correct' => '["getelementbyid"]',
                'difficulty' => 35,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой HTTP-код означает "Перенаправление"?',
                'correct' => '["301", "302"]',
                'difficulty' => 40,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой язык используется для создания анимаций и интерактивности на веб-страницах?',
                'correct' => '["javascript"]',
                'difficulty' => 45,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тег HTML используется для создания формы?',
                'correct' => '["<form>", "form"]',
                'difficulty' => 40,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод JavaScript используется для выполнения HTTP-запроса?',
                'correct' => '["fetch", "xmlhttprequest"]',
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой язык используется для создания стилей в веб-разработке?',
                'correct' => '["css"]',
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тег HTML используется для создания кнопки?',
                'correct' => '["<button>", "button"]',
                'difficulty' => 45,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой HTTP-код означает "Успешное создание ресурса"?',
                'correct' => '["201"]',
                'difficulty' => 30,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод JavaScript используется для преобразования объекта в JSON-строку?',
                'correct' => '["json.stringify"]',
                'difficulty' => 30,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой механизм используется для защиты от CSRF-атак в веб-приложениях?',
                'correct' => '["csrf-token", "csrf токен"]',
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой протокол используется для реального времени в веб-приложениях (чат, уведомления)?',
                'correct' => '["websocket"]',
                'difficulty' => 20,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой препроцессор CSS добавляет функции вроде переменных и миксинов?',
                'correct' => '["sass", "scss", "less"]',
                'difficulty' => 30,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой язык является надмножеством JavaScript с строгой типизацией?',
                'correct' => '["typescript"]',
                'difficulty' => 35,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Как называется технология для создания переиспользуемых компонентов в вебе?',
                'correct' => '["web components"]',
                'difficulty' => 15,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой запрос GraphQL используется для получения данных?',
                'correct' => '["query"]',
                'difficulty' => 20,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой стандарт используется для аутентификации через JSON-токены?',
                'correct' => '["jwt"]',
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой инструмент используется для контейнеризации приложений?',
                'correct' => '["docker"]',
                'difficulty' => 30,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой заголовок HTTP управляет кешированием ресурсов в браузере?',
                'correct' => '["cache-control"]',
                'difficulty' => 35,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какая команда Git используется для клонирования репозитория?',
                'correct' => '["git clone"]',
                'difficulty' => 40,
            ],

            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равно число π с точностью до двух знаков после запятой?',
                'correct' => json_encode(['3.14']),
                'difficulty' => 30,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Как называется результат сложения двух чисел?',
                'correct' => json_encode(['сумма']),
                'difficulty' => 20,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равен квадратный корень из 64?',
                'correct' => json_encode(['8']),
                'difficulty' => 40,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Как называется фигура с тремя сторонами?',
                'correct' => json_encode(['треугольник']),
                'difficulty' => 10,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равно 5 в степени 3?',
                'correct' => json_encode(['125']),
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Как называется число, которое делится только на 1 и на само себя?',
                'correct' => json_encode(['простое']),
                'difficulty' => 25,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равно 12 умножить на 12?',
                'correct' => json_encode(['144']),
                'difficulty' => 35,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Как называется число, которое обозначает отсутствие количества?',
                'correct' => json_encode(['ноль', '0']),
                'difficulty' => 15,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равен периметр квадрата со стороной 5 см?',
                'correct' => json_encode(['20 см', '20']),
                'difficulty' => 45,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Как называется операция, обратная сложению?',
                'correct' => json_encode(['вычитание']),
                'difficulty' => 20,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равна площадь круга с радиусом 3 метра (π ≈ 3.14)?',
                'correct' => json_encode(['28.26', '28.26 м²']),
                'difficulty' => 55,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Решите уравнение: 2x + 3 = 7',
                'correct' => json_encode(['2', 'x=2']),
                'difficulty' => 45,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Как называется число, обратное 5?',
                'correct' => json_encode(['0.2', '1/5']),
                'difficulty' => 35,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равна сумма углов в треугольнике?',
                'correct' => json_encode(['180', '180°', '180 градусов']),
                'difficulty' => 25,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Как называется график квадратичной функции?',
                'correct' => json_encode(['парабола']),
                'difficulty' => 40,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равно 25% от 200?',
                'correct' => json_encode(['50']),
                'difficulty' => 30,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Назовите формулу теоремы Пифагора',
                'correct' => json_encode(['a²+b²=c²', 'c² = a² + b²']),
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равен объём куба с ребром 4 см?',
                'correct' => json_encode(['64 см³', '64']),
                'difficulty' => 60,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Как называется число, которое умножают на другое в операции умножения?',
                'correct' => json_encode(['множитель']),
                'difficulty' => 15,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Решите пример: (8 + 2) × 3 − 4',
                'correct' => json_encode(['26']),
                'difficulty' => 40,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равен синус 30 градусов?',
                'correct' => json_encode(['0.5']),
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Как называется число, которое получается при делении одного числа на другое?',
                'correct' => json_encode(['частное']),
                'difficulty' => 20,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равно произведение 7 и 8?',
                'correct' => json_encode(['56']),
                'difficulty' => 30,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Как называется число, которое стоит перед переменной в алгебраическом выражении?',
                'correct' => json_encode(['коэффициент']),
                'difficulty' => 40,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равен логарифм 100 по основанию 10?',
                'correct' => json_encode(['2']),
                'difficulty' => 55,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Как называется фигура, у которой все стороны и углы равны?',
                'correct' => json_encode(['правильный многоугольник']),
                'difficulty' => 25,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равна сумма чисел от 1 до 10?',
                'correct' => json_encode(['55']),
                'difficulty' => 35,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Как называется график линейной функции?',
                'correct' => json_encode(['прямая']),
                'difficulty' => 15,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равен тангенс 45 градусов?',
                'correct' => json_encode(['1']),
                'difficulty' => 45,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Решите уравнение: x² - 9 = 0',
                'correct' => json_encode(['3', '-3', 'x=3', 'x=-3']),
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равен косинус 60 градусов?',
                'correct' => json_encode(['0.5']),
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Как называется число, которое прибавляют к другому в операции сложения?',
                'correct' => json_encode(['слагаемое']),
                'difficulty' => 20,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равно 10 в степени 2?',
                'correct' => json_encode(['100']),
                'difficulty' => 30,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Как называется фигура, у которой четыре стороны и все углы прямые?',
                'correct' => json_encode(['прямоугольник']),
                'difficulty' => 25,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равен периметр прямоугольника со сторонами 4 см и 6 см?',
                'correct' => json_encode(['20 см', '20']),
                'difficulty' => 40,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Решите уравнение: 3x - 5 = 10',
                'correct' => json_encode(['5', 'x=5']),
                'difficulty' => 45,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Как называется число, которое обозначает отношение длины окружности к её диаметру?',
                'correct' => json_encode(['π', 'пи']),
                'difficulty' => 35,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равно 15% от 300?',
                'correct' => json_encode(['45']),
                'difficulty' => 30,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Как называется число, которое является результатом вычитания?',
                'correct' => json_encode(['разность']),
                'difficulty' => 15,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равна площадь треугольника с основанием 5 см и высотой 4 см?',
                'correct' => json_encode(['10 см²', '10']),
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равно значение выражения 2 + 2?',
                'correct' => json_encode(['4']),
                'difficulty' => 90,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Сколько градусов в сумме углов треугольника?',
                'correct' => json_encode(['180']),
                'difficulty' => 80,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равен квадратный корень из 25?',
                'correct' => json_encode(['5']),
                'difficulty' => 85,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Как называется многоугольник с шестью сторонами?',
                'correct' => json_encode(['шестиугольник', 'гексагон']),
                'difficulty' => 70,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равно 10 в квадрате?',
                'correct' => json_encode(['100']),
                'difficulty' => 85,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Как называется результат сложения?',
                'correct' => json_encode(['сумма']),
                'difficulty' => 75,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равно значение выражения 15 - 7?',
                'correct' => json_encode(['8']),
                'difficulty' => 88,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Как называется число, которое делится только на 1 и само себя?',
                'correct' => json_encode(['простое число', 'простое']),
                'difficulty' => 60,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равна половина от 100?',
                'correct' => json_encode(['50']),
                'difficulty' => 90,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Как называется число, стоящее в числителе дроби?',
                'correct' => json_encode(['числитель']),
                'difficulty' => 70,
            ],
        ]);
    }
}
