<?php

namespace Database\Seeders\Quest;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChoiceQuestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('choice_quests')->insert([
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тег HTML используется для создания заголовка первого уровня?',
                'correct' => '["<h1>"]',
                'uncorrect' => '["<header>", "<head>", "<title>"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какое CSS-свойство отвечает за изменение типа отображения элемента (блок/строка)?',
                'correct' => '["display"]',
                'uncorrect' => '["position", "float", "visibility"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод JavaScript позволяет выполнить код асинхронно через указанное время?',
                'correct' => '["setTimeout()"]',
                'uncorrect' => '["setInterval()", "async()", "wait()"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой HTTP-статус соответствует ошибке "Страница не найдена"?',
                'correct' => '["404"]',
                'uncorrect' => '["200", "403", "500"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какая SQL-инъекция считается безопасной практикой для защиты от атак?',
                'correct' => '["Подготовленные выражения (prepared statements)"]',
                'uncorrect' => '["Использование mysql_real_escape_string()", "Конкатенация строк запроса", "Фильтрация через регулярные выражения"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод HTTP используется для отправки данных на сервер (например, формы)?',
                'correct' => '["POST"]',
                'uncorrect' => '["GET", "PUT", "DELETE"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какая технология используется для хранения данных на стороне клиента между сессиями?',
                'correct' => '["Все перечисленные"]',
                'uncorrect' => '["LocalStorage", "SessionStorage", "Cookie"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Что такое RESTful API?',
                'correct' => '["Архитектурный стиль для создания веб-сервисов"]',
                'uncorrect' => '["Язык программирования", "Библиотека для работы с базами данных", "Протокол шифрования"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой инструмент используется для управления зависимостями в JavaScript-проектах?',
                'correct' => '["npm"]',
                'uncorrect' => '["pip", "composer", "gradle"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Что такое React.js?',
                'correct' => '["Библиотека для построения пользовательских интерфейсов"]',
                'uncorrect' => '["Фреймворк для создания серверных приложений", "Библиотека для работы с базами данных", "Язык программирования"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тег HTML используется для создания ссылки?',
                'correct' => '["<a>"]',
                'uncorrect' => '["<link>", "<href>", "<url>"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какое CSS-свойство используется для задания внешних отступов элемента?',
                'correct' => '["margin"]',
                'uncorrect' => '["padding", "border", "outline"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод JavaScript используется для преобразования строки в число?',
                'correct' => '["parseInt()"]',
                'uncorrect' => '["toString()", "toNumber()", "convertToNumber()"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой HTTP-метод используется для обновления данных на сервере?',
                'correct' => '["PUT"]',
                'uncorrect' => '["POST", "PATCH", "DELETE"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тип данных в JavaScript является неизменяемым?',
                'correct' => '["string"]',
                'uncorrect' => '["array", "object", "function"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой инструмент используется для контроля версий в разработке?',
                'correct' => '["Git"]',
                'uncorrect' => '["SVN", "Mercurial", "CVS"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод массива в JavaScript возвращает новый массив, отфильтрованный по условию?',
                'correct' => '["filter()"]',
                'uncorrect' => '["map()", "reduce()", "forEach()"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тег HTML используется для вставки изображения?',
                'correct' => '["<img>"]',
                'uncorrect' => '["<image>", "<picture>", "<src>"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой HTTP-статус соответствует успешному выполнению запроса?',
                'correct' => '["200"]',
                'uncorrect' => '["201", "301", "400"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод JavaScript используется для добавления элемента в конец массива?',
                'correct' => '["push()"]',
                'uncorrect' => '["pop()", "shift()", "unshift()"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тег HTML используется для создания списка с нумерацией?',
                'correct' => '["<ol>"]',
                'uncorrect' => '["<ul>", "<li>", "<dl>"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какое CSS-свойство используется для задания внутренних отступов элемента?',
                'correct' => '["padding"]',
                'uncorrect' => '["margin", "border", "outline"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод JavaScript используется для поиска элемента в массиве?',
                'correct' => '["find()"]',
                'uncorrect' => '["search()", "locate()", "filter()"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой HTTP-метод используется для удаления данных на сервере?',
                'correct' => '["DELETE"]',
                'uncorrect' => '["POST", "PUT", "PATCH"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тип данных в JavaScript используется для хранения ключ-значение?',
                'correct' => '["object"]',
                'uncorrect' => '["array", "string", "number"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой инструмент используется для сборки JavaScript-проектов?',
                'correct' => '["Webpack"]',
                'uncorrect' => '["Grunt", "Gulp", "Babel"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод массива в JavaScript возвращает новый массив, преобразованный по условию?',
                'correct' => '["map()"]',
                'uncorrect' => '["filter()", "reduce()", "forEach()"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тег HTML используется для создания таблицы?',
                'correct' => '["<table>"]',
                'uncorrect' => '["<tr>", "<td>", "<th>"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой HTTP-статус соответствует перенаправлению?',
                'correct' => '["301"]',
                'uncorrect' => '["200", "404", "500"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод JavaScript используется для удаления последнего элемента массива?',
                'correct' => '["pop()"]',
                'uncorrect' => '["push()", "shift()", "unshift()"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие HTTP-методы являются безопасными (не изменяют состояние сервера)?',
                'correct' => '["GET", "HEAD"]', // Два правильных ответа
                'uncorrect' => '["POST", "PUT", "DELETE"]',
                'is_multiple' => 1,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие теги HTML используются для создания таблицы?',
                'correct' => '["<table>", "<tr>", "<td>"]', // Три правильных ответа
                'uncorrect' => '["<div>", "<span>", "<ul>"]',
                'is_multiple' => 1,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие методы массива в JavaScript возвращают новый массив?',
                'correct' => '["map()", "filter()", "slice()"]', // Три правильных ответа
                'uncorrect' => '["push()", "pop()", "splice()"]',
                'is_multiple' => 1,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие HTTP-статусы соответствуют ошибкам на стороне клиента?',
                'correct' => '["400", "404", "403"]', // Три правильных ответа
                'uncorrect' => '["500", "503", "200"]',
                'is_multiple' => 1,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие типы данных в JavaScript являются примитивными?',
                'correct' => '["string", "number", "boolean"]', // Три правильных ответа
                'uncorrect' => '["object", "array", "function"]',
                'is_multiple' => 1,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие CSS-свойства используются для работы с текстом?',
                'correct' => '["font-size", "text-align", "color"]', // Три правильных ответа
                'uncorrect' => '["margin", "padding", "border"]',
                'is_multiple' => 1,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие методы JavaScript используются для работы с асинхронным кодом?',
                'correct' => '["Promise", "async/await", "setTimeout()"]', // Три правильных ответа
                'uncorrect' => '["forEach()", "map()", "filter()"]',
                'is_multiple' => 1,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие теги HTML используются для создания форм?',
                'correct' => '["<form>", "<input>", "<button>"]', // Три правильных ответа
                'uncorrect' => '["<div>", "<span>", "<table>"]',
                'is_multiple' => 1,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие HTTP-методы являются идемпотентными?',
                'correct' => '["GET", "PUT", "DELETE"]', // Три правильных ответа
                'uncorrect' => '["POST", "PATCH"]',
                'is_multiple' => 1,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие инструменты используются для сборки и управления зависимостями в JavaScript?',
                'correct' => '["npm", "Webpack", "Babel"]', // Три правильных ответа
                'uncorrect' => '["Git", "Docker", "Jenkins"]',
                'is_multiple' => 1,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие методы жизненного цикла React используются для оптимизации производительности?',
                'correct' => '["shouldComponentUpdate", "React.memo()"]',
                'uncorrect' => '["componentDidMount", "render", "constructor"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие алгоритмы лежат в основе работы Virtual DOM в React?',
                'correct' => '["Diffing Algorithm", "Reconciliation"]',
                'uncorrect' => '["Bubble Sort", "Dijkstra Algorithm", "Binary Search"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие заголовки HTTP помогают защититься от XSS-атак?',
                'correct' => '["Content-Security-Policy", "X-XSS-Protection"]',
                'uncorrect' => '["Cache-Control", "Accept-Encoding", "User-Agent"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие методы JavaScript являются чистыми функциями (pure functions)?',
                'correct' => '["Math.sqrt()", "Object.freeze()"]',
                'uncorrect' => '["Date.now()", "Math.random()", "Array.push()"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие типы данных передаются по ссылке в JavaScript?',
                'correct' => '["Object", "Array"]',
                'uncorrect' => '["string", "number", "boolean"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие паттерны используются для управления состоянием в больших React-приложениях?',
                'correct' => '["Flux", "Redux"]',
                'uncorrect' => '["Singleton", "Factory", "Observer"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие Web API позволяют работать с многопоточностью в браузере?',
                'correct' => '["Web Workers", "Service Workers"]',
                'uncorrect' => '["WebSocket", "LocalStorage", "IndexedDB"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие оптимизации применяются для уменьшения времени загрузки SPA?',
                'correct' => '["Code Splitting", "Lazy Loading"]',
                'uncorrect' => '["Inline CSS", "Server-Side Rendering", "HTTP/1.1"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие методы позволяют предотвратить SQL-инъекции в PHP?',
                'correct' => '["Использование PDO с prepared statements", "Использование mysqli_real_escape_string()"]',
                'uncorrect' => '["Фильтрация через htmlspecialchars()", "Ручная конкатенация строк"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие особенности WebAssembly делают его быстрее JavaScript?',
                'correct' => '["Статическая типизация", "Предкомпиляция в бинарный код"]',
                'uncorrect' => '["Динамическая типизация", "Интерпретация в браузере"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],

            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих функций имеют предел при x → 0?',
                'correct' => '["f(x) = x²", "f(x) = sin(x)/x"]',
                'uncorrect' => '["f(x) = 1/x", "f(x) = ln(x)"]',
                'is_multiple' => true,
                'difficulty' => 60,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих утверждений верны для предела функции?',
                'correct' => '["Предел функции может не существовать", "Предел функции может быть равен бесконечности"]',
                'uncorrect' => '["Предел функции всегда существует", "Предел функции всегда конечен"]',
                'is_multiple' => true,
                'difficulty' => 55,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих функций имеют предел при x → ∞?',
                'correct' => '["f(x) = 1/x", "f(x) = e^(-x)"]',
                'uncorrect' => '["f(x) = x²", "f(x) = ln(x)"]',
                'is_multiple' => true,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих функций являются бесконечно малыми при x → 0?',
                'correct' => '["f(x) = x", "f(x) = sin(x)"]',
                'uncorrect' => '["f(x) = 1/x", "f(x) = e^x"]',
                'is_multiple' => true,
                'difficulty' => 65,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих функций имеют предел при x → 1?',
                'correct' => '["f(x) = x", "f(x) = (x² - 1)/(x - 1)"]',
                'uncorrect' => '["f(x) = 1/(x - 1)", "f(x) = ln(x - 1)"]',
                'is_multiple' => true,
                'difficulty' => 60,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих утверждений верны для непрерывных функций?',
                'correct' => '["Непрерывная функция имеет предел в каждой точке", "Предел непрерывной функции равен значению функции в точке"]',
                'uncorrect' => '["Непрерывная функция может не иметь предела", "Предел непрерывной функции всегда равен нулю"]',
                'is_multiple' => true,
                'difficulty' => 55,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих функций имеют предел при x → ∞?',
                'correct' => '["f(x) = 1/x²", "f(x) = e^(-x)"]',
                'uncorrect' => '["f(x) = x", "f(x) = ln(x)"]',
                'is_multiple' => true,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих функций являются бесконечно большими при x → ∞?',
                'correct' => '["f(x) = x²", "f(x) = e^x"]',
                'uncorrect' => '["f(x) = 1/x", "f(x) = sin(x)"]',
                'is_multiple' => true,
                'difficulty' => 60,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих функций имеют предел при x → 0?',
                'correct' => '["f(x) = sin(x)/x", "f(x) = x³"]',
                'uncorrect' => '["f(x) = 1/x", "f(x) = ln(x)"]',
                'is_multiple' => true,
                'difficulty' => 55,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих утверждений верны для предела функции?',
                'correct' => '["Предел функции может быть равен нулю", "Предел функции может быть равен бесконечности"]',
                'uncorrect' => '["Предел функции всегда существует", "Предел функции всегда конечен"]',
                'is_multiple' => true,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Что такое предел функции?',
                'correct' => '["Значение, к которому стремится функция при приближении аргумента к заданной точке"]',
                'uncorrect' => '["Значение функции в точке", "Производная функции", "Интеграл функции"]',
                'is_multiple' => false,
                'difficulty' => 60,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какое из следующих утверждений верно для предела функции f(x) = x² при x → 2?',
                'correct' => '["Предел равен 4"]',
                'uncorrect' => '["Предел равен 2", "Предел не существует", "Предел равен 0"]',
                'is_multiple' => false,
                'difficulty' => 55,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какое из следующих выражений является неопределенностью?',
                'correct' => '["0/0"]',
                'uncorrect' => '["1/2", "5/0", "∞/1"]',
                'is_multiple' => false,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какое из следующих утверждений верно для предела функции f(x) = 1/x при x → ∞?',
                'correct' => '["Предел равен 0"]',
                'uncorrect' => '["Предел равен 1", "Предел равен ∞", "Предел не существует"]',
                'is_multiple' => false,
                'difficulty' => 60,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какое из следующих утверждений верно для предела функции f(x) = sin(x)/x при x → 0?',
                'correct' => '["Предел равен 1"]',
                'uncorrect' => '["Предел равен 0", "Предел равен ∞", "Предел не существует"]',
                'is_multiple' => false,
                'difficulty' => 55,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Соотнесите термины и их определения:',
                'correct' => '["Предел функции - значение, к которому стремится функция", "Непрерывность - равенство предела функции и её значения в точке", "Бесконечно малая - функция, предел которой равен нулю"]',
                'uncorrect' => '["Предел функции - значение функции в точке", "Непрерывность - отсутствие разрывов на графике", "Бесконечно малая - функция, предел которой равен бесконечности"]',
                'is_multiple' => true,
                'difficulty' => 65,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Соотнесите термины и их определения:',
                'correct' => '["Производная - скорость изменения функции", "Предел - значение, к которому стремится функция", "Интеграл - площадь под кривой"]',
                'uncorrect' => '["Производная - значение функции в точке", "Предел - значение функции на бесконечности", "Интеграл - предел функции"]',
                'is_multiple' => true,
                'difficulty' => 60,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих функций являются бесконечно малыми при x → 0?',
                'correct' => '["f(x) = x", "f(x) = sin(x)"]',
                'uncorrect' => '["f(x) = 1/x", "f(x) = e^x"]',
                'is_multiple' => true,
                'difficulty' => 55,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих функций имеют предел при x → ∞?',
                'correct' => '["f(x) = 1/x", "f(x) = e^(-x)"]',
                'uncorrect' => '["f(x) = x²", "f(x) = ln(x)"]',
                'is_multiple' => true,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих утверждений верны для предела функции?',
                'correct' => '["Предел функции может быть равен нулю", "Предел функции может быть равен бесконечности"]',
                'uncorrect' => '["Предел функции всегда существует", "Предел функции всегда конечен"]',
                'is_multiple' => true,
                'difficulty' => 55,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какое из следующих утверждений верно для предела функции f(x) = (x² - 1)/(x - 1) при x → 1?',
                'correct' => '["Предел равен 2"]',
                'uncorrect' => '["Предел равен 0", "Предел равен 1", "Предел не существует"]',
                'is_multiple' => false,
                'difficulty' => 60,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какое из следующих утверждений верно для предела функции f(x) = (x³ - 8)/(x - 2) при x → 2?',
                'correct' => '["Предел равен 12"]',
                'uncorrect' => '["Предел равен 6", "Предел равен 0", "Предел не существует"]',
                'is_multiple' => false,
                'difficulty' => 55,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какое из следующих утверждений верно для предела функции f(x) = (1 + 1/x)^x при x → ∞?',
                'correct' => '["Предел равен e"]',
                'uncorrect' => '["Предел равен 1", "Предел равен 0", "Предел не существует"]',
                'is_multiple' => false,
                'difficulty' => 65,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какое из следующих утверждений верно для предела функции f(x) = ln(x) при x → 1?',
                'correct' => '["Предел равен 0"]',
                'uncorrect' => '["Предел равен 1", "Предел равен ∞", "Предел не существует"]',
                'is_multiple' => false,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какое из следующих утверждений верно для предела функции f(x) = e^x при x → -∞?',
                'correct' => '["Предел равен 0"]',
                'uncorrect' => '["Предел равен 1", "Предел равен ∞", "Предел не существует"]',
                'is_multiple' => false,
                'difficulty' => 55,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Соотнесите термины и их определения:',
                'correct' => '["Предел функции - значение, к которому стремится функция", "Непрерывность - равенство предела функции и её значения в точке", "Бесконечно малая - функция, предел которой равен нулю"]',
                'uncorrect' => '["Предел функции - значение функции в точке", "Непрерывность - отсутствие разрывов на графике", "Бесконечно малая - функция, предел которой равен бесконечности"]',
                'is_multiple' => true,
                'difficulty' => 60,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Соотнесите термины и их определения:',
                'correct' => '["Производная - скорость изменения функции", "Предел - значение, к которому стремится функция", "Интеграл - площадь под кривой"]',
                'uncorrect' => '["Производная - значение функции в точке", "Предел - значение функции на бесконечности", "Интеграл - предел функции"]',
                'is_multiple' => true,
                'difficulty' => 55,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих функций являются бесконечно малыми при x → 0?',
                'correct' => '["f(x) = x", "f(x) = sin(x)"]',
                'uncorrect' => '["f(x) = 1/x", "f(x) = e^x"]',
                'is_multiple' => true,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих функций имеют предел при x → ∞?',
                'correct' => '["f(x) = 1/x", "f(x) = e^(-x)"]',
                'uncorrect' => '["f(x) = x²", "f(x) = ln(x)"]',
                'is_multiple' => true,
                'difficulty' => 55,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих утверждений верны для предела функции?',
                'correct' => '["Предел функции может быть равен нулю", "Предел функции может быть равен бесконечности"]',
                'uncorrect' => '["Предел функции всегда существует", "Предел функции всегда конечен"]',
                'is_multiple' => true,
                'difficulty' => 60,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Тело движется по закону s(t) = 2t³ - 3t. Чему равна скорость в момент t=1?',
                'correct' => '["3"]',
                'uncorrect' => '["2", "6", "0"]',
                'is_multiple' => false,
                'difficulty' => 60,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какое правило дифференцирования применяется для функции f(x) = sin(x²)?',
                'correct' => '["Цепное правило"]',
                'uncorrect' => '["Правило произведения", "Правило суммы", "Правило частного"]',
                'is_multiple' => false,
                'difficulty' => 55,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Соотнесите физические понятия и их математические аналоги:',
                'correct' => '["Скорость - первая производная пути", "Ускорение - вторая производная пути", "Сила - производная импульса"]',
                'uncorrect' => '["Скорость - интеграл пути", "Ускорение - первая производная скорости", "Сила - вторая производная массы"]',
                'is_multiple' => true,
                'difficulty' => 65,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих функций имеют точку максимума при x=0?',
                'correct' => '["f(x) = -x²", "f(x) = -|x|"]',
                'uncorrect' => '["f(x) = x³", "f(x) = e^x"]',
                'is_multiple' => true,
                'difficulty' => 60,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равна производная функции f(x) = ln(x² + 1)?',
                'correct' => '["(2x)/(x² + 1)"]',
                'uncorrect' => '["1/(x² + 1)", "2x", "2x/(x²)"]',
                'is_multiple' => false,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих утверждений верны для производной сложной функции?',
                'correct' => '["Используется цепное правило", "Производная внешней функции умножается на производную внутренней"]',
                'uncorrect' => '["Производная равна сумме производных", "Не требует применения специальных правил"]',
                'is_multiple' => true,
                'difficulty' => 55,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Соотнесите функции и их производные:',
                'correct' => '["sin(x) → cos(x)", "e^x → e^x", "x³ → 3x²"]',
                'uncorrect' => '["cos(x) → sin(x)", "ln(x) → 1/x²", "2x → x²"]',
                'is_multiple' => true,
                'difficulty' => 70,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'При каком условии функция имеет горизонтальную асимптоту?',
                'correct' => '["Если предел функции при x → ∞ равен конечному числу"]',
                'uncorrect' => '["Если функция не имеет разрывов", "Если производная функции равна нулю", "Если функция периодическая"]',
                'is_multiple' => false,
                'difficulty' => 60,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих функций являются недифференцируемыми в точке x=0?',
                'correct' => '["f(x) = |x|", "f(x) = x^(1/3)"]',
                'uncorrect' => '["f(x) = x²", "f(x) = sin(x)"]',
                'is_multiple' => true,
                'difficulty' => 65,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равна производная неявной функции x² + y² = 25 в точке (3,4)?',
                'correct' => '["-3/4"]',
                'uncorrect' => '["3/4", "4/3", "-4/3"]',
                'is_multiple' => false,
                'difficulty' => 70,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих функций имеют вертикальную асимптоту при x=0?',
                'correct' => '["f(x) = 1/x", "f(x) = ln(x)"]',
                'uncorrect' => '["f(x) = x²", "f(x) = sin(x)"]',
                'is_multiple' => true,
                'difficulty' => 60,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какое из следующих утверждений верно для функции f(x) = x³?',
                'correct' => '["Функция имеет точку перегиба при x=0"]',
                'uncorrect' => '["Функция имеет максимум при x=0", "Функция имеет минимум при x=0", "Функция не имеет точек перегиба"]',
                'is_multiple' => false,
                'difficulty' => 55,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Соотнесите функции и их производные:',
                'correct' => '["cos(x) → -sin(x)", "e^(2x) → 2e^(2x)", "ln(x) → 1/x"]',
                'uncorrect' => '["sin(x) → -cos(x)", "e^x → e^(x+1)", "x² → 2x²"]',
                'is_multiple' => true,
                'difficulty' => 65,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих функций являются непрерывными на всей числовой прямой?',
                'correct' => '["f(x) = x³", "f(x) = sin(x)"]',
                'uncorrect' => '["f(x) = 1/x", "f(x) = ln(x)"]',
                'is_multiple' => true,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равна производная функции f(x) = x·e^x?',
                'correct' => '["e^x + x·e^x"]',
                'uncorrect' => '["e^x", "x·e^x", "e^x + x"]',
                'is_multiple' => false,
                'difficulty' => 60,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих утверждений верны для функции f(x) = |x|?',
                'correct' => '["Функция не дифференцируема в точке x=0", "Функция имеет минимум при x=0"]',
                'uncorrect' => '["Функция дифференцируема в точке x=0", "Функция имеет максимум при x=0"]',
                'is_multiple' => true,
                'difficulty' => 55,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Соотнесите функции и их вторые производные:',
                'correct' => '["x³ → 6x", "sin(x) → -sin(x)", "e^x → e^x"]',
                'uncorrect' => '["x² → 2x", "cos(x) → cos(x)", "ln(x) → 1/x²"]',
                'is_multiple' => true,
                'difficulty' => 70,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих функций имеют горизонтальную асимптоту при y=0?',
                'correct' => '["f(x) = 1/x", "f(x) = e^(-x)"]',
                'uncorrect' => '["f(x) = x²", "f(x) = ln(x)"]',
                'is_multiple' => true,
                'difficulty' => 60,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равна производная функции f(x) = (x² + 1)/(x - 1) в точке x=2?',
                'correct' => '["5"]',
                'uncorrect' => '["3", "4", "6"]',
                'is_multiple' => false,
                'difficulty' => 65,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих утверждений верны для функции f(x) = x·sin(x)?',
                'correct' => '["Функция имеет бесконечно много точек перегиба", "Функция не имеет асимптот"]',
                'uncorrect' => '["Функция имеет максимум при x=0", "Функция имеет вертикальную асимптоту"]',
                'is_multiple' => true,
                'difficulty' => 70,
            ]
        ]);
    }
}
