<?php

namespace Database\Seeders\Quest;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChoiceQuestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('choice_quests')->insert([
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тег HTML используется для создания заголовка первого уровня?',
                'correct' => '["<h1>"]',
                'uncorrect' => '["<header>", "<head>", "<title>"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какое CSS-свойство отвечает за изменение типа отображения элемента (блок/строка)?',
                'correct' => '["display"]',
                'uncorrect' => '["position", "float", "visibility"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод JavaScript позволяет выполнить код асинхронно через указанное время?',
                'correct' => '["setTimeout()"]',
                'uncorrect' => '["setInterval()", "async()", "wait()"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой HTTP-статус соответствует ошибке "Страница не найдена"?',
                'correct' => '["404"]',
                'uncorrect' => '["200", "403", "500"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какая SQL-инъекция считается безопасной практикой для защиты от атак?',
                'correct' => '["Подготовленные выражения (prepared statements)"]',
                'uncorrect' => '["Использование mysql_real_escape_string()", "Конкатенация строк запроса", "Фильтрация через регулярные выражения"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод HTTP используется для отправки данных на сервер (например, формы)?',
                'correct' => '["POST"]',
                'uncorrect' => '["GET", "PUT", "DELETE"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какая технология используется для хранения данных на стороне клиента между сессиями?',
                'correct' => '["Все перечисленные"]',
                'uncorrect' => '["LocalStorage", "SessionStorage", "Cookie"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Что такое RESTful API?',
                'correct' => '["Архитектурный стиль для создания веб-сервисов"]',
                'uncorrect' => '["Язык программирования", "Библиотека для работы с базами данных", "Протокол шифрования"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой инструмент используется для управления зависимостями в JavaScript-проектах?',
                'correct' => '["npm"]',
                'uncorrect' => '["pip", "composer", "gradle"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Что такое React.js?',
                'correct' => '["Библиотека для построения пользовательских интерфейсов"]',
                'uncorrect' => '["Фреймворк для создания серверных приложений", "Библиотека для работы с базами данных", "Язык программирования"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тег HTML используется для создания ссылки?',
                'correct' => '["<a>"]',
                'uncorrect' => '["<link>", "<href>", "<url>"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какое CSS-свойство используется для задания внешних отступов элемента?',
                'correct' => '["margin"]',
                'uncorrect' => '["padding", "border", "outline"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод JavaScript используется для преобразования строки в число?',
                'correct' => '["parseInt()"]',
                'uncorrect' => '["toString()", "toNumber()", "convertToNumber()"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой HTTP-метод используется для обновления данных на сервере?',
                'correct' => '["PUT"]',
                'uncorrect' => '["POST", "PATCH", "DELETE"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тип данных в JavaScript является неизменяемым?',
                'correct' => '["string"]',
                'uncorrect' => '["array", "object", "function"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой инструмент используется для контроля версий в разработке?',
                'correct' => '["Git"]',
                'uncorrect' => '["SVN", "Mercurial", "CVS"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод массива в JavaScript возвращает новый массив, отфильтрованный по условию?',
                'correct' => '["filter()"]',
                'uncorrect' => '["map()", "reduce()", "forEach()"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тег HTML используется для вставки изображения?',
                'correct' => '["<img>"]',
                'uncorrect' => '["<image>", "<picture>", "<src>"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой HTTP-статус соответствует успешному выполнению запроса?',
                'correct' => '["200"]',
                'uncorrect' => '["201", "301", "400"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод JavaScript используется для добавления элемента в конец массива?',
                'correct' => '["push()"]',
                'uncorrect' => '["pop()", "shift()", "unshift()"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тег HTML используется для создания списка с нумерацией?',
                'correct' => '["<ol>"]',
                'uncorrect' => '["<ul>", "<li>", "<dl>"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какое CSS-свойство используется для задания внутренних отступов элемента?',
                'correct' => '["padding"]',
                'uncorrect' => '["margin", "border", "outline"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод JavaScript используется для поиска элемента в массиве?',
                'correct' => '["find()"]',
                'uncorrect' => '["search()", "locate()", "filter()"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой HTTP-метод используется для удаления данных на сервере?',
                'correct' => '["DELETE"]',
                'uncorrect' => '["POST", "PUT", "PATCH"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тип данных в JavaScript используется для хранения ключ-значение?',
                'correct' => '["object"]',
                'uncorrect' => '["array", "string", "number"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой инструмент используется для сборки JavaScript-проектов?',
                'correct' => '["Webpack"]',
                'uncorrect' => '["Grunt", "Gulp", "Babel"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод массива в JavaScript возвращает новый массив, преобразованный по условию?',
                'correct' => '["map()"]',
                'uncorrect' => '["filter()", "reduce()", "forEach()"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой тег HTML используется для создания таблицы?',
                'correct' => '["<table>"]',
                'uncorrect' => '["<tr>", "<td>", "<th>"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой HTTP-статус соответствует перенаправлению?',
                'correct' => '["301"]',
                'uncorrect' => '["200", "404", "500"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какой метод JavaScript используется для удаления последнего элемента массива?',
                'correct' => '["pop()"]',
                'uncorrect' => '["push()", "shift()", "unshift()"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие HTTP-методы являются безопасными (не изменяют состояние сервера)?',
                'correct' => '["GET", "HEAD"]', // Два правильных ответа
                'uncorrect' => '["POST", "PUT", "DELETE"]',
                'is_multiple' => 1,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие теги HTML используются для создания таблицы?',
                'correct' => '["<table>", "<tr>", "<td>"]', // Три правильных ответа
                'uncorrect' => '["<div>", "<span>", "<ul>"]',
                'is_multiple' => 1,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие методы массива в JavaScript возвращают новый массив?',
                'correct' => '["map()", "filter()", "slice()"]', // Три правильных ответа
                'uncorrect' => '["push()", "pop()", "splice()"]',
                'is_multiple' => 1,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие HTTP-статусы соответствуют ошибкам на стороне клиента?',
                'correct' => '["400", "404", "403"]', // Три правильных ответа
                'uncorrect' => '["500", "503", "200"]',
                'is_multiple' => 1,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие типы данных в JavaScript являются примитивными?',
                'correct' => '["string", "number", "boolean"]', // Три правильных ответа
                'uncorrect' => '["object", "array", "function"]',
                'is_multiple' => 1,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие CSS-свойства используются для работы с текстом?',
                'correct' => '["font-size", "text-align", "color"]', // Три правильных ответа
                'uncorrect' => '["margin", "padding", "border"]',
                'is_multiple' => 1,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие методы JavaScript используются для работы с асинхронным кодом?',
                'correct' => '["Promise", "async/await", "setTimeout()"]', // Три правильных ответа
                'uncorrect' => '["forEach()", "map()", "filter()"]',
                'is_multiple' => 1,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие теги HTML используются для создания форм?',
                'correct' => '["<form>", "<input>", "<button>"]', // Три правильных ответа
                'uncorrect' => '["<div>", "<span>", "<table>"]',
                'is_multiple' => 1,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие HTTP-методы являются идемпотентными?',
                'correct' => '["GET", "PUT", "DELETE"]', // Три правильных ответа
                'uncorrect' => '["POST", "PATCH"]',
                'is_multiple' => 1,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие инструменты используются для сборки и управления зависимостями в JavaScript?',
                'correct' => '["npm", "Webpack", "Babel"]', // Три правильных ответа
                'uncorrect' => '["Git", "Docker", "Jenkins"]',
                'is_multiple' => 1,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие методы жизненного цикла React используются для оптимизации производительности?',
                'correct' => '["shouldComponentUpdate", "React.memo()"]',
                'uncorrect' => '["componentDidMount", "render", "constructor"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие алгоритмы лежат в основе работы Virtual DOM в React?',
                'correct' => '["Diffing Algorithm", "Reconciliation"]',
                'uncorrect' => '["Bubble Sort", "Dijkstra Algorithm", "Binary Search"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие заголовки HTTP помогают защититься от XSS-атак?',
                'correct' => '["Content-Security-Policy", "X-XSS-Protection"]',
                'uncorrect' => '["Cache-Control", "Accept-Encoding", "User-Agent"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие методы JavaScript являются чистыми функциями (pure functions)?',
                'correct' => '["Math.sqrt()", "Object.freeze()"]',
                'uncorrect' => '["Date.now()", "Math.random()", "Array.push()"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие типы данных передаются по ссылке в JavaScript?',
                'correct' => '["Object", "Array"]',
                'uncorrect' => '["string", "number", "boolean"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие паттерны используются для управления состоянием в больших React-приложениях?',
                'correct' => '["Flux", "Redux"]',
                'uncorrect' => '["Singleton", "Factory", "Observer"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие Web API позволяют работать с многопоточностью в браузере?',
                'correct' => '["Web Workers", "Service Workers"]',
                'uncorrect' => '["WebSocket", "LocalStorage", "IndexedDB"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие оптимизации применяются для уменьшения времени загрузки SPA?',
                'correct' => '["Code Splitting", "Lazy Loading"]',
                'uncorrect' => '["Inline CSS", "Server-Side Rendering", "HTTP/1.1"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие методы позволяют предотвратить SQL-инъекции в PHP?',
                'correct' => '["Использование PDO с prepared statements", "Использование mysqli_real_escape_string()"]',
                'uncorrect' => '["Фильтрация через htmlspecialchars()", "Ручная конкатенация строк"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Какие особенности WebAssembly делают его быстрее JavaScript?',
                'correct' => '["Статическая типизация", "Предкомпиляция в бинарный код"]',
                'uncorrect' => '["Динамическая типизация", "Интерпретация в браузере"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],

            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какое из следующих чисел является простым?',
                'correct' => '["7"]',
                'uncorrect' => '["4", "9", "15"]',
                'is_multiple' => 0,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих чисел являются чётными?',
                'correct' => '["2", "4", "6"]',
                'uncorrect' => '["1", "3", "5"]',
                'is_multiple' => 1,
                'difficulty' => 75,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равно значение выражения 2 + 2 * 2?',
                'correct' => '["6"]',
                'uncorrect' => '["8", "4", "10"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих чисел являются квадратами целых чисел?',
                'correct' => '["1", "4", "9"]',
                'uncorrect' => '["2", "3", "5"]',
                'is_multiple' => 1,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какое из следующих чисел является корнем уравнения x² - 5x + 6 = 0?',
                'correct' => '["2", "3"]',
                'uncorrect' => '["1", "4"]',
                'is_multiple' => 1,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равно значение выражения log₂(8)?',
                'correct' => '["3"]',
                'uncorrect' => '["2", "4", "1"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих чисел являются делителями числа 12?',
                'correct' => '["1", "2", "3", "4", "6"]',
                'uncorrect' => '["5", "7", "8"]',
                'is_multiple' => 1,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих утверждений верны для треугольника со сторонами 3, 4, 5?',
                'correct' => '["Это прямоугольный треугольник", "Его площадь равна 6"]',
                'uncorrect' => '["Это равносторонний треугольник", "Его периметр равен 10"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих чисел являются членами последовательности Фибоначчи?',
                'correct' => '["0", "1", "2", "3", "5"]',
                'uncorrect' => '["4", "6", "7"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих чисел являются иррациональными?',
                'correct' => '["π", "√2"]',
                'uncorrect' => '["1", "2.5", "3/4"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какое из следующих чисел является квадратом целого числа?',
                'correct' => '["16"]',
                'uncorrect' => '["15", "17", "18"]',
                'is_multiple' => 0,
                'difficulty' => 35,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равно значение выражения (3 + 5) * 2?',
                'correct' => '["16"]',
                'uncorrect' => '["10", "13", "20"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равен квадратный корень из 64?',
                'correct' => '["8"]',
                'uncorrect' => '["4", "6", "10"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равно значение выражения 3² + 4²?',
                'correct' => '["25"]',
                'uncorrect' => '["5", "12", "18"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какое из следующих чисел является кубом целого числа?',
                'correct' => '["8"]',
                'uncorrect' => '["6", "9", "10"]',
                'is_multiple' => 0,
                'difficulty' => 40,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих чисел являются делителями числа 18?',
                'correct' => '["1", "2", "3", "6", "9"]',
                'uncorrect' => '["4", "5", "7"]',
                'is_multiple' => 1,
                'difficulty' => 35,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равно значение выражения 5! (факториал)?',
                'correct' => '["120"]',
                'uncorrect' => '["60", "100", "150"]',
                'is_multiple' => 0,
                'difficulty' => 45,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих чисел являются степенями двойки?',
                'correct' => '["2", "4", "8"]',
                'uncorrect' => '["3", "5", "6"]',
                'is_multiple' => 1,
                'difficulty' => 30,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равно значение выражения log₂(8)?',
                'correct' => '["3"]',
                'uncorrect' => '["2", "4", "5"]',
                'is_multiple' => 0,
                'difficulty' => 40,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих чисел являются корнями уравнения x² - 5x + 6 = 0?',
                'correct' => '["2", "3"]',
                'uncorrect' => '["1", "4", "5"]',
                'is_multiple' => 1,
                'difficulty' => 35,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равно значение выражения sin(π/2)?',
                'correct' => '["1"]',
                'uncorrect' => '["0", "0.5", "2"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из следующих чисел являются целыми?',
                'correct' => '["-1", "0", "1"]',
                'uncorrect' => '["0.5", "1.5", "2.3"]',
                'is_multiple' => 1,
                'difficulty' => 30,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равно значение выражения 2³ + 3²?',
                'correct' => '["17"]',
                'uncorrect' => '["10", "12", "15"]',
                'is_multiple' => 0,
                'difficulty' => 45,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равна площадь круга с радиусом 3?',
                'correct' => '["9π"]',
                'uncorrect' => '["6π", "3π", "12π"]',
                'is_multiple' => 0,
                'difficulty' => 40,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какое выражение равно 3/4 + 1/2?',
                'correct' => '["5/4"]',
                'uncorrect' => '["4/6", "1.25", "3/6"]',
                'is_multiple' => 0,
                'difficulty' => 35,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => '20% от 150 равно:',
                'correct' => '["30"]',
                'uncorrect' => '["20", "25", "35"]',
                'is_multiple' => 0,
                'difficulty' => 30,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Сумма углов треугольника равна:',
                'correct' => '["180°"]',
                'uncorrect' => '["90°", "270°", "360°"]',
                'is_multiple' => 0,
                'difficulty' => 50,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Число 10 в двоичной системе счисления:',
                'correct' => '["1010"]',
                'uncorrect' => '["1001", "1100", "1111"]',
                'is_multiple' => 0,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Вероятность выпадения орла при подбрасывании монеты:',
                'correct' => '["1/2"]',
                'uncorrect' => '["1/4", "1/3", "2/3"]',
                'is_multiple' => 0,
                'difficulty' => 45,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Объём куба с ребром 2 метра:',
                'correct' => '["8 м³"]',
                'uncorrect' => '["4 м³", "6 м³", "10 м³"]',
                'is_multiple' => 0,
                'difficulty' => 40,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Решите уравнение: 2x + 5 = 15',
                'correct' => '["5"]',
                'uncorrect' => '["3", "10", "7.5"]',
                'is_multiple' => 0,
                'difficulty' => 30,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Наибольший общий делитель (НОД) чисел 12 и 18:',
                'correct' => '["6"]',
                'uncorrect' => '["3", "4", "9"]',
                'is_multiple' => 0,
                'difficulty' => 35,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из этих чисел являются степенями числа 5?',
                'correct' => '["25", "125"]',
                'uncorrect' => '["10", "50", "75"]',
                'is_multiple' => 1,
                'difficulty' => 20,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Чему равна сумма первых 5 натуральных чисел?',
                'correct' => '["15"]',
                'uncorrect' => '["10", "12", "20"]',
                'is_multiple' => 0,
                'difficulty' => 40,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из тригонометрических тождеств верны?',
                'correct' => '["sin²x + cos²x = 1", "1 + tan²x = sec²x"]',
                'uncorrect' => '["cosx = 1/sinx", "tanx = sinx + cosx"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Площадь поверхности куба с ребром 3 см:',
                'correct' => '["54 см²"]',
                'uncorrect' => '["27 см²", "36 см²", "45 см²"]',
                'is_multiple' => 0,
                'difficulty' => 35,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Сколько диагоналей в пятиугольнике?',
                'correct' => '["5"]',
                'uncorrect' => '["3", "4", "6"]',
                'is_multiple' => 0,
                'difficulty' => 30,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какое число является решением уравнения eˣ = 1?',
                'correct' => '["0"]',
                'uncorrect' => '["1", "e", "-1"]',
                'is_multiple' => 0,
                'difficulty' => 45,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Объём цилиндра (r=2, h=5):',
                'correct' => '["20π"]',
                'uncorrect' => '["10π", "25π", "40π"]',
                'is_multiple' => 0,
                'difficulty' => 30,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Сколько существует комбинаций из 3 букв слова "МАТЬ"?',
                'correct' => '["24"]',
                'uncorrect' => '["12", "6", "8"]',
                'is_multiple' => 0,
                'difficulty' => 20,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из чисел являются мнимыми?',
                'correct' => '["i", "2i", "√(-4)"]',
                'uncorrect' => '["-1", "0", "3.14"]',
                'is_multiple' => 1,
                'difficulty' => 15,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Среднее арифметическое чисел 4, 5, 6 и 9:',
                'correct' => '["6"]',
                'uncorrect' => '["5", "5.5", "6.5"]',
                'is_multiple' => 0,
                'difficulty' => 45,
            ],
            [
                'topic_id' => 2,
                'vis' => 1,
                'quest' => 'Какие из утверждений верны для параллелограмма?',
                'correct' => '["Противоположные стороны равны", "Диагонали делятся пополам"]',
                'uncorrect' => '["Все углы прямые", "Диагонали равны"]',
                'is_multiple' => 1,
                'difficulty' => 25,
            ],
        ]);
    }
}
