<?php

namespace Database\Seeders\Quest;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RelationQuestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('relation_quests')->insert([
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите языки программирования с их основным предназначением.',
                'first_column' => json_encode(['HTML', 'CSS', 'JavaScript', 'PHP', 'SQL']),
                'second_column' => json_encode(['Разметка веб-страницы', 'Стилизация страниц', 'Динамическое поведение', 'Серверная логика', 'Работа с базами данных']),
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите HTTP-методы с их назначением.',
                'first_column' => json_encode(['GET', 'POST', 'PUT', 'DELETE', 'PATCH']),
                'second_column' => json_encode(['Получение данных', 'Отправка данных', 'Обновление ресурса', 'Удаление ресурса', 'Частичное обновление']),
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите элементы HTML с их предназначением.',
                'first_column' => json_encode(['<div>', '<span>', '<a>', '<form>', '<table>']),
                'second_column' => json_encode(['Блочный контейнер', 'Строчный контейнер', 'Гиперссылка', 'Форма для отправки данных', 'Таблица']),
                'difficulty' => 60,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите популярные фреймворки с языками программирования.',
                'first_column' => json_encode(['React', 'Laravel', 'Django', 'Vue', 'Spring']),
                'second_column' => json_encode(['JavaScript', 'PHP', 'Python', 'JavaScript', 'Java']),
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите уровни HTTP-ответов с их назначением.',
                'first_column' => json_encode(['1xx', '2xx', '3xx', '4xx', '5xx']),
                'second_column' => json_encode(['Информационные', 'Успешные', 'Перенаправления', 'Ошибки клиента', 'Ошибки сервера']),
                'difficulty' => 55,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите типы данных JavaScript с их примерами.',
                'first_column' => json_encode(['String', 'Number', 'Boolean', 'Array', 'Object']),
                'second_column' => json_encode(['"Hello"', '42', 'true/false', '[1, 2, 3]', '{"key": "value"}']),
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите CSS-свойства с их назначением.',
                'first_column' => json_encode(['color', 'font-size', 'margin', 'padding', 'display']),
                'second_column' => json_encode(['Цвет текста', 'Размер шрифта', 'Внешний отступ', 'Внутренний отступ', 'Тип отображения элемента']),
                'difficulty' => 60,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите способы хранения данных в браузере с их характеристиками.',
                'first_column' => json_encode(['Cookies', 'LocalStorage', 'SessionStorage', 'IndexedDB', 'Cache API']),
                'second_column' => json_encode(['Хранение небольших данных, отправляемых на сервер', 'Долговременное хранение данных в браузере', 'Хранение данных на время сессии', 'База данных в браузере', 'Кеширование ресурсов для работы оффлайн']),
                'difficulty' => 65,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите ключевые концепции ООП с их описанием.',
                'first_column' => json_encode(['Абстракция', 'Инкапсуляция', 'Наследование', 'Полиморфизм']),
                'second_column' => json_encode(['Скрытие деталей реализации', 'Сокрытие данных внутри объекта', 'Передача свойств и методов от родителя к потомку', 'Использование одного интерфейса для разных типов данных']),
                'difficulty' => 55,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите типы атак на веб-приложения с их описанием.',
                'first_column' => json_encode(['SQL-инъекция', 'XSS', 'CSRF', 'DDoS', 'Brute Force']),
                'second_column' => json_encode(['Внедрение SQL-кода', 'Внедрение вредоносного скрипта', 'Атака через поддельные запросы', 'Перегрузка сервера запросами', 'Перебор паролей']),
                'difficulty' => 70,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите форматы изображений с их особенностями.',
                'first_column' => json_encode(['JPEG', 'PNG', 'GIF', 'SVG', 'WEBP']),
                'second_column' => json_encode(['Сжатие с потерями', 'Поддержка прозрачности', 'Анимация', 'Векторная графика', 'Современный формат сжатия']),
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите основные HTTP-заголовки с их назначением.',
                'first_column' => json_encode(['Content-Type', 'Authorization', 'Cache-Control', 'User-Agent', 'Accept']),
                'second_column' => json_encode(['Тип содержимого', 'Аутентификация пользователя', 'Настройки кэширования', 'Идентификация клиента', 'Форматы данных, поддерживаемые клиентом']),
                'difficulty' => 55,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите виды API с их описанием.',
                'first_column' => json_encode(['REST', 'SOAP', 'GraphQL', 'gRPC', 'WebSocket']),
                'second_column' => json_encode(['Стандартный API на основе HTTP', 'Протокол обмена на XML', 'Гибкий API с запросами данных', 'Высокопроизводительный RPC API', 'Двусторонняя связь в реальном времени']),
                'difficulty' => 60,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите принципы SOLID с их кратким описанием.',
                'first_column' => json_encode(['Single Responsibility', 'Open/Closed', 'Liskov Substitution', 'Interface Segregation', 'Dependency Inversion']),
                'second_column' => json_encode(['Одна ответственность на класс', 'Открыто для расширения, закрыто для изменения', 'Замена подклассов без изменения поведения', 'Разделение интерфейсов на небольшие', 'Зависимости должны строиться на абстракциях']),
                'difficulty' => 65,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите типы данных в SQL с их применением.',
                'first_column' => json_encode(['VARCHAR', 'TEXT', 'INT', 'FLOAT', 'BOOLEAN']),
                'second_column' => json_encode(['Строки переменной длины', 'Длинные тексты', 'Целые числа', 'Числа с плавающей запятой', 'Логическое значение']),
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите способы аутентификации с их характеристиками.',
                'first_column' => json_encode(['Basic Auth', 'OAuth', 'JWT', 'SAML', 'API Key']),
                'second_column' => json_encode(['Простая аутентификация через логин/пароль', 'Авторизация через сторонние сервисы', 'Токен на основе JSON', 'Протокол единого входа', 'Ключ доступа к API']),
                'difficulty' => 60,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите элементы Flexbox с их назначением.',
                'first_column' => json_encode(['justify-content', 'align-items', 'flex-wrap', 'order', 'align-self']),
                'second_column' => json_encode(['Выравнивание по основной оси', 'Выравнивание по поперечной оси', 'Перенос строк', 'Определение порядка элементов', 'Выравнивание конкретного элемента']),
                'difficulty' => 55,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите принципы безопасности с их значением.',
                'first_column' => json_encode(['Confidentiality', 'Integrity', 'Availability', 'Non-Repudiation', 'Authentication']),
                'second_column' => json_encode(['Конфиденциальность данных', 'Целостность данных', 'Доступность данных', 'Невозможность отрицания действий', 'Подтверждение личности']),
                'difficulty' => 65,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите виды тестирования безопасности с их описанием.',
                'first_column' => json_encode(['Penetration Testing', 'Vulnerability Assessment', 'Security Audit', 'Threat Modeling', 'Code Review']),
                'second_column' => json_encode(['Проверка защиты через атаки', 'Анализ уязвимостей', 'Аудит безопасности системы', 'Определение возможных угроз', 'Анализ исходного кода на безопасность']),
                'difficulty' => 70,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите популярные базы данных с их характеристиками.',
                'first_column' => json_encode(['MySQL', 'PostgreSQL', 'MongoDB', 'Redis', 'SQLite']),
                'second_column' => json_encode(['Реляционная СУБД', 'Расширенная реляционная СУБД', 'Документо-ориентированная БД', 'Ключ-значение БД', 'Легковесная встроенная БД']),
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите популярные CSS-препроцессоры с их особенностями.',
                'first_column' => json_encode(['SASS', 'LESS', 'Stylus', 'PostCSS', 'SCSS']),
                'second_column' => json_encode(['Поддержка вложенности и переменных', 'Компактный синтаксис', 'Гибкая настройка', 'Плагинная архитектура', 'Расширенный синтаксис CSS']),
                'difficulty' => 55,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите фреймворки JavaScript с их ключевыми особенностями.',
                'first_column' => json_encode(['React', 'Vue', 'Angular', 'Svelte', 'Next.js']),
                'second_column' => json_encode(['Компонентный подход, виртуальный DOM', 'Реактивность и простота', 'Полноценный MVC-фреймворк', 'Компиляция в нативный JavaScript', 'Фреймворк для SSR и статических сайтов']),
                'difficulty' => 60,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите популярные CMS с их особенностями.',
                'first_column' => json_encode(['WordPress', 'Joomla', 'Drupal', 'Magento', 'Ghost']),
                'second_column' => json_encode(['Самая популярная CMS', 'Гибкая система управления контентом', 'Сложная, но мощная CMS', 'Ориентирована на e-commerce', 'Минималистичный движок для блогов']),
                'difficulty' => 55,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите основные шаблоны проектирования с их предназначением.',
                'first_column' => json_encode(['Singleton', 'Factory Method', 'Observer', 'Decorator', 'Strategy']),
                'second_column' => json_encode(['Гарантирует единственный экземпляр', 'Создает объекты через фабрику', 'Подписка на события', 'Декорирование объектов', 'Выбор поведения во время выполнения']),
                'difficulty' => 65,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите способы хранения состояния в React.',
                'first_column' => json_encode(['useState', 'useReducer', 'Context API', 'Redux', 'Recoil']),
                'second_column' => json_encode(['Локальное состояние компонента', 'Сложное состояние с редюсерами', 'Глобальное состояние через контекст', 'Централизованное хранилище', 'Современный атомарный подход']),
                'difficulty' => 60,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите виды атак на веб-приложения с их механизмами.',
                'first_column' => json_encode(['SQL-инъекция', 'XSS', 'CSRF', 'DDoS', 'Brute Force']),
                'second_column' => json_encode(['Внедрение SQL-кода в запросы', 'Внедрение вредоносного JavaScript', 'Подмена запросов от имени пользователя', 'Перегрузка сервера трафиком', 'Перебор паролей']),
                'difficulty' => 70,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите основные принципы REST API.',
                'first_column' => json_encode(['Stateless', 'Client-Server', 'Cacheable', 'Layered System', 'Uniform Interface']),
                'second_column' => json_encode(['Сервер не хранит состояние клиента', 'Клиент и сервер независимы', 'Клиент может кэшировать данные', 'Многоуровневая архитектура', 'Единообразный доступ к ресурсам']),
                'difficulty' => 65,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите атрибуты HTML-форм с их назначением.',
                'first_column' => json_encode(['action', 'method', 'name', 'autocomplete', 'novalidate']),
                'second_column' => json_encode(['URL-адрес для отправки данных', 'Метод запроса (GET/POST)', 'Имя элемента формы', 'Автозаполнение полей', 'Отключение встроенной валидации']),
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите способы оптимизации производительности веб-сайта.',
                'first_column' => json_encode(['Минификация', 'Lazy Loading', 'CDN', 'Gzip', 'Code Splitting']),
                'second_column' => json_encode(['Сжатие кода CSS и JS', 'Отложенная загрузка контента', 'Распределение ресурсов по серверам', 'Сжатие HTTP-ответов', 'Разделение кода на модули']),
                'difficulty' => 55,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите популярные алгоритмы сортировки с их сложностью.',
                'first_column' => json_encode(['Bubble Sort', 'Merge Sort', 'Quick Sort', 'Heap Sort', 'Insertion Sort']),
                'second_column' => json_encode(['O(n^2)', 'O(n log n)', 'O(n log n)', 'O(n log n)', 'O(n^2)']),
                'difficulty' => 60,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите уровни HTTP-кодов с их значением.',
                'first_column' => json_encode(['1xx', '2xx', '3xx', '4xx', '5xx']),
                'second_column' => json_encode(['Информационные', 'Успешные', 'Перенаправления', 'Ошибки клиента', 'Ошибки сервера']),
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите основные структуры данных с их особенностями.',
                'first_column' => json_encode(['Array', 'Linked List', 'Stack', 'Queue', 'Hash Table']),
                'second_column' => json_encode(['Набор элементов с индексами', 'Связанный список узлов', 'Стек LIFO', 'Очередь FIFO', 'Хранение пар ключ-значение']),
                'difficulty' => 55,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите основные принципы асинхронного программирования.',
                'first_column' => json_encode(['Callback', 'Promise', 'Async/Await', 'Event Loop', 'Concurrency']),
                'second_column' => json_encode(['Функции обратного вызова', 'Объект для обработки асинхронных данных', 'Современный синтаксис для работы с асинхронностью', 'Цикл обработки событий', 'Параллельное выполнение задач']),
                'difficulty' => 65,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите принципы CSS с их описанием.',
                'first_column' => json_encode(['Specificity', 'Inheritance', 'Cascade', 'Flexbox', 'Grid']),
                'second_column' => json_encode(['Приоритетность правил', 'Наследование стилей', 'Последовательность применения правил', 'Макет на основе гибких контейнеров', 'Макет на основе сетки']),
                'difficulty' => 55,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите основные директивы SQL с их функциями.',
                'first_column' => json_encode(['SELECT', 'INSERT', 'UPDATE', 'DELETE', 'JOIN']),
                'second_column' => json_encode(['Выборка данных', 'Добавление данных', 'Обновление данных', 'Удаление данных', 'Объединение таблиц']),
                'difficulty' => 50,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите уровни кеширования с их характеристиками.',
                'first_column' => json_encode(['Browser Cache', 'CDN Cache', 'Server Cache', 'Database Cache', 'Memory Cache']),
                'second_column' => json_encode(['Кеширование в браузере пользователя', 'Кеширование на периферийных серверах', 'Кеширование на сервере', 'Кеширование в базе данных', 'Кеширование в оперативной памяти']),
                'difficulty' => 60,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите фреймворки бэкенда с их языками программирования.',
                'first_column' => json_encode(['Django', 'Express.js', 'Laravel', 'Spring', 'FastAPI']),
                'second_column' => json_encode(['Python', 'JavaScript', 'PHP', 'Java', 'Python']),
                'difficulty' => 55,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите основные уязвимости веб-приложений с их рисками.',
                'first_column' => json_encode(['SQL Injection', 'XSS', 'CSRF', 'Broken Authentication', 'Security Misconfiguration']),
                'second_column' => json_encode(['Использование SQL-запросов для атак', 'Использование вредоносного JavaScript', 'Фальсификация запросов от имени пользователя', 'Небезопасная аутентификация', 'Ошибки конфигурации системы безопасности']),
                'difficulty' => 70,
            ],
            [
                'topic_id' => 1,
                'vis' => 1,
                'quest' => 'Соотнесите основные принципы DevOps с их описанием.',
                'first_column' => json_encode(['CI/CD', 'Infrastructure as Code', 'Monitoring', 'Logging', 'Automation']),
                'second_column' => json_encode(['Непрерывная интеграция и развертывание', 'Описание инфраструктуры в коде', 'Мониторинг работы системы', 'Логирование событий', 'Автоматизация процессов разработки и развертывания']),
                'difficulty' => 65,
            ],

        ]);
    }
}
